# Generated by Django 4.2.19 on 2025-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrado', '0003_alter_usuario_apellido_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
